services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quickestimate-prod-app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: quickestimate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_TLS: "False"
      SMTP_SSL: "False"

  db:
    image: postgres:14
    container_name: quickestimate-prod-db
    environment:
      POSTGRES_DB: quickestimate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
      interval: 2s
      timeout: 3s
      retries: 30

  mailhog:
    image: mailhog/mailhog:latest
    container_name: quickestimate-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
