services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quickestimate-prod-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: quickestimate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_TLS: "False"
      SMTP_SSL: "False"

  db:
    image: postgres:14
    container_name: quickestimate-prod-db
    environment:
      POSTGRES_DB: quickestimate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    container_name: quickestimate-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
