version: '3.8'

services:
  backend:
    build: ./backend
    container_name: quickestimate-backend
    volumes:
      - ./backend:/app
      - ./data:/app/config
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: quickestimate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USER:
      SMTP_PASSWORD:
      SMTP_TLS: "false"
      SMTP_SSL: "false"
      SMTP_SENDER: "no-reply@example.com"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: quickestimate-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  db:
    image: postgres:14
    container_name: quickestimate-db
    environment:
      POSTGRES_DB: quickestimate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: quickestimate-mailhog
    ports:
      - "1025:1025"  # SMTP порт
      - "8025:8025"  # Web-интерфейс

volumes:
  pgdata:
